### PR TITLE
Add React on Client example

### PR DESCRIPTION
**Pull request by venikman**
Part of #19

### CODE REVIEW

**Comment by danrasmuson** [comment]
It be lovely to merge this PR. Is it blocked by anything? Can I help?

**Comment by sholladay** [comment]
@danrasmuson agreed, let's get this fixed up and merged. At the moment, this example doesn't actually work because it requires a build step, which isn't accounted for.

We need to either:
A. Build the app and commit the `app.js` file to the git repo. That would make it easier for people to run the example, but then `app.js` has to be kept in sync with changes to the source and it bloats the git repo because it will include all of React.
B. Update the example's instructions to include the build step. I think I'd prefer this approach, but I'm open to alternatives. 

Assuming we go with B, then we should consider how the user will actually run the build. Should the instructions have the user run the `mkdir -p build` and `deno bundle` commands or should they just have something like `sh -c "$(curl -fsSL https://raw.githubusercontent.com/sholladay/pogo/master/react-on-client/build.sh)";`? I'm leaning towards the former. The latter could be a standard across all of the examples, which would be nice, but some people might be afraid of running a remote shell script like that. There may be other alternatives I haven't considered.

**Comment by danrasmuson** [comment]
Okay. Lovely. I have time on Wednesday to give it a go.

**Comment by danrasmuson** [comment]
@sholladay I followed your directions as I understood them and put a PR #69

**Comment by sholladay** [comment]
Closing in favor of #69, which contains the commits from this PR (meaning you'll still get credit).

**Pull request closed without merging**
